### ISSUE TITLE
请教，这个站是否某种文档生成工具构建的？

### ISSUE THREAD

**Issue by maxyou** [betweens/Material#2]
象这个站：https://www.no-forget.com/material/#/
你是用什么文档构建工具做的，还是自己一页一页编辑，贴上去的？那么工作量很大呀。
包括这个：https://www.no-forget.com/react-router/web/guides/philosophy

谢谢。

**Comment by betweens** [comment]
> 象这个站：https://www.no-forget.com/material/#/
> 你是用什么文档构建工具做的，还是自己一页一页编辑，贴上去的？那么工作量很大呀。
> 包括这个：https://www.no-forget.com/react-router/web/guides/philosophy
> 
> 谢谢。

materia文档是自己搭建的架构写的

react-router-v4中文文档是由官方的源码clone一份,翻译其中的doc部分，编译即可
